//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftGameEFDataModel.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SoftcrylicEntities : DbContext
    {
        public SoftcrylicEntities()
            : base("name=SoftcrylicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<GamesInfo> GamesInfoes { get; set; }
        public virtual DbSet<ActiveUser> ActiveUsers { get; set; }
        public virtual DbSet<ActiveUsers1> ActiveUsers1 { get; set; }
    }
}
